Improve error message when functions:shell command fails due to missing project association. (#6088)
**Before**:

```
$ firebase functions:shell
Error: An unexpected error has occurred.
```

**After**:

```
$  firebase functions:shell
Error: No currently active project.
To run this command, you need to specify a project. You have two options:
- Run this command with --project <alias_or_project_id>.
- Set an active project by running firebase use --add, then rerun this command.
To list all the Firebase projects to which you have access, run firebase projects:list.
To learn about active projects for the CLI, visit https://firebase.google.com/docs/cli#project_aliases
```

Fixes https://github.com/firebase/firebase-tools/issues/6070