Compat mode bug bash fixes (#7680)
* Ignore invalid connector errors in Using Google Analytics in DEBUG mode. Emulators (+ UI) events will be shown in GA Debug View only.

Error: No currently active project.
To run this command, you need to specify a project. You have two options:
- Run this command with --project <alias_or_project_id>.
- Set an active project by running firebase use --add, then rerun this command.
To list all the Firebase projects to which you have access, run firebase projects:list.
To learn about active projects for the CLI, visit https://firebase.google.com/docs/cli#project_aliases.

* Update schema migration prompt wording.

* Another prompt message wording update.

---------

Co-authored-by: joehan <joehanley@google.com>