Fix bug where scheduled CF3 deploys unexpectedly succeeded with invalid Cloud Scheduler configurations. (#2609)
Today, deploying scheduled CF3 with invalid cloud scheduler config unexpectedly succeeds:

```js
// functions/index.js
exports.scheduledHello = functions.pubsub
    .schedule('* * * * *')
    .timeZone('INVALID TIMEZONE')
    .onRun(async context => {
        functions.logger.info("hello world");
        return null;
    });
```
```shell
$ firebase deploy --only functions:scheduledHello
...
✔  scheduler: required API cloudscheduler.googleapis.com is enabled
✔  pubsub: required API pubsub.googleapis.com is enabled
✔  functions: created scheduler job firebase-schedule-scheduledHello-us-central1
✔  functions[scheduledHello(us-central1)]: Successful update operation.

✔  Deploy complete!
```

We end up with a broken setup where Cloud Function and Cloud Pubsub topics are deployed without a Cloud Scheduler job.

With the fix, the deployment will fail instead:

```shell
$ firebase deploy --only functions:scheduledHello
...
✔  scheduler: required API cloudscheduler.googleapis.com is enabled
✔  pubsub: required API pubsub.googleapis.com is enabled

Error: HTTP Error: 400, Schedule or time zone is invalid.
```

Neither Cloud Function or Pubsub topic are created since creating Cloud Scheduler job is done before Functions of Pubsub creation.

Fixes https://github.com/firebase/firebase-tools/issues/1835.