Increases timeOut for detectFromPort to avoid sporadic deployment fails
Fixes: 
Root cause of following error
Error: User code failed to load. Cannot determine backend specification